---
title: "About This Project"
---


## About crime data

first draft, change anything if you would like --Hongyao

```{r}
library(tidyverse)
library(readxl)
```

```{r}
# load data and clean up column names
# not to omit NAs
crime = readxl::read_excel("./data/crime-data-2016.xls", range = ("A4:W202")) %>% 
  janitor::clean_names() %>% 
    rename_(population = names(.)[3],
          violent_crime_number = names(.)[4],
          violent_crime_rate = names(.)[5],
          murder_manslaughter_number = names(.)[6],
          murder_manslaughter_rate = names(.)[7],
          rape_revise_number = names(.)[8],
          rape_revise_rate = names(.)[9],
          rape_legacy_number = names(.)[10],
          rape_legacy_rate = names(.)[11],
          robbery_number = names(.)[12],
          robbery_rate = names(.)[13],
          aggravated_assault_number = names(.)[14],
          aggravated_assault_rate = names(.)[15],
          property_crime_number = names(.)[16],
          property_crime_rate = names(.)[17],
          burglary_number = names(.)[18],
          burglary_rate = names(.)[19],
          larceny_theft_number = names(.)[20],
          larceny_theft_rate = names(.)[21],
          motor_vehicle_theft_number = names(.)[22],
          motor_vehicle_theft_rate = names(.)[23]) %>% 
  mutate(area = as.factor(area)) 
crime[,2:23] <- as.numeric(unlist(crime[,2:23]))

# fill up area name
i = 1
for(i in 0:65) {
  n = 3 * i + 1
  crime$area[n + 1] = paste0(crime$area[n]) 
  crime$area[n + 2] = paste0(crime$area[n])
  i = i + 1
}

# check head
head(crime)
```

Group by districts(i.e. Northeast, Midwest, South, West), each district can be subdivide into smaller categories(e.g. Northeast can be divided into New England and Middle Atlantic), which is not explored at the moment(but could be later)

Change anything if you want (HX)

```{r}
# rank areas by average violent crime rate from 2015 to 2016
crime %>% 
  group_by(area) %>% 
  filter(year != "Percent change") %>%
  summarise_each(funs(mean)) %>%
  mutate(area = fct_reorder(area, violent_crime_rate)) %>% 
  ggplot(aes(x = area, y = violent_crime_rate)) +
  geom_point() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size = 8),
        title = element_text(size = 6))
```

```{r data cleaning on crime dataset}
# Filter out "percent change" in "year" variable
crime_clean = 
  crime %>%
  filter(year != "NA")

# Create a new dataframe to store the data of different large areas
crime_largearea = 
  crime_clean %>%
  filter(area %in% c("United States Total", "Northeast", "Midwest", "South", "West"))

# Create subtotal for each big areas
crime_northeast = 
  crime_clean %>%
  filter(area %in% c("New England", "Middle Atlantic"))

crime_midwest = 
  crime_clean %>%
  filter(area %in% c("East North Central", "West North Central"))

crime_south = 
  crime_clean %>%
  filter(area %in% c("South Atlantic", "East South Central", "West South Central"))

crime_west = 
  crime_clean %>%
  filter(area %in% c("Mountain", "Pacific", "Puerto Rico"))

# Change the name of "area" to "state"
colnames(crime_clean)[1] = "state"

# Filter out these areas in the tidied dataset
crime_clean = 
  crime_clean %>%
  filter(!state %in% c("United States Total", "Northeast", "Midwest", "South", "West", "New England", "Middle Atlantic", "East North Central", "West North Central", "South Atlantic", "East South Central", "West South Central", "Mountain", "Pacific", "Puerto Rico"))
```


















