---
title: "drug code supplementary"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(PerformanceAnalytics)
library(rvest)
library(httr)
library(gridExtra)
library(flexdashboard)
library(viridis)
library(plotly)
library(gsheet)
```


Data cleaning

```{r}
drug_raw =
  read_csv("https://think.cs.vt.edu/corgis/csv/drugs/drugs.csv?forcedownload=1/drugs.csv") %>%
  janitor::clean_names()
drug_clean = 
  drug_raw %>%
  select(year, state,
         rates_alcohol_abuse_past_year_12_17:rates_alcohol_dependence_past_year_26,
         rates_alcohol_need_treatment_past_year_12_17:rates_illicit_drugs_abuse_past_month_26, 
         rates_illicit_drugs_cocaine_used_past_year_12_17:rates_illicit_drugs_need_treatment_past_year_26,
         rates_marijuana_new_users_12_17:rates_marijuana_used_past_year_26) %>%
  gather(key, value, -state, -year) %>% 
  mutate(key = str_replace_all(key, c("year_" = "year:", "month_" = "month:", "risk_" = "risk:", "users_" = "users:"))) %>%
  separate(key, into = c("rate", "age"), sep = ":", extra = "merge") %>%
  mutate(rate = str_replace(rate, "^rates_", "")) %>% 
  spread(key = rate, value = value)
```



## Explore alcohol use with different degree by state and year

* **Alcohol use by state**

```{r alcohol_use_state,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>% 
  group_by(state) %>% 
  summarize(mean_alcohol_abuse = mean(alcohol_abuse_past_year),
            mean_alcohol_binge = mean(alcohol_binge_past_month),
            mean_alcohol_dependence = mean(alcohol_dependence_past_year),
            mean_alcoh_treatment = mean(alcohol_need_treatment_past_year)) %>% 
  gather(key = "degree", value = "rate", -state) %>% 
  ggplot(aes(x = state, y = rate)) +
  geom_bar(aes(fill = degree), stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Alcohol use in each state by degree",
    x = "State",
    y = "Rate of alcohol use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")
```


```{r alcohol_use,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>% 
  group_by(state, age) %>% 
  summarize(mean_alcohol_abuse = mean(alcohol_abuse_past_year),
            mean_alcohol_binge = mean(alcohol_binge_past_month),
            mean_alcohol_dependence = mean(alcohol_dependence_past_year),
            mean_alcoh_treatment = mean(alcohol_need_treatment_past_year),
            mean_alcohol_use = mean(alcohol_use_past_month)) %>% 
  ggplot(aes(x = state, y = mean_alcohol_abuse)) +
  geom_bar(aes(fill = age), stat = "identity") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Alcohol abuse in each state by age",
    x = "State",
    y = "Rate of alcohol abuse",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")

drug_clean %>% 
  group_by(state, age) %>% 
  summarize(mean_alcohol_binge = mean(alcohol_binge_past_month)) %>% 
  ggplot(aes(x = state, y = mean_alcohol_binge)) +
  geom_bar(aes(fill = age), stat = "identity") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Alcohol binge in each state by age",
    x = "State",
    y = "Rate of alcohol binge",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")

drug_clean %>% 
  group_by(state, age) %>% 
  summarize(mean_alcohol_dependence = mean(alcohol_dependence_past_year)) %>% 
  ggplot(aes(x = state, y = mean_alcohol_dependence)) +
  geom_bar(aes(fill = age), stat = "identity") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Alcohol dependence in each state by age",
    x = "State",
    y = "Rate of alcohol dependence",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")

drug_clean %>% 
  group_by(state, age) %>% 
  summarize(mean_alcoh_treatment = mean(alcohol_need_treatment_past_year)) %>% 
  ggplot(aes(x = state, y = mean_alcoh_treatment)) +
  geom_bar(aes(fill = age), stat = "identity") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Alcohol use need treatment in each state by age",
    x = "State",
    y = "Rate of alcohol use need treatment",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")
```

* **Alcohol use by year**

```{r alcohol_use_year,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>% 
  group_by(year) %>% 
  summarize(mean_alcohol_abuse = mean(alcohol_abuse_past_year),
            mean_alcohol_binge = mean(alcohol_binge_past_month),
            mean_alcohol_dependence = mean(alcohol_dependence_past_year),
            mean_alcoh_treatment = mean(alcohol_need_treatment_past_year)) %>% 
  gather(key = "degree", value = "rate", -year) %>% 
  ggplot(aes(x = year, y = rate)) +
  geom_line(aes(color = degree)) +
  theme_bw() +
  labs(
    title = "Alcohol use through years by degree",
    x = "Year",
    y = "Rate of alcohol use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom") +
  scale_x_continuous(breaks = c(2002:2014))
```

## Explore other drugs

* **Cocaine**

* Illicit drug use by year

```{r illicit_use_year,echo=FALSE,warning=FALSE,message=FALSE}
  drug_clean %>% 
  select(year, contains("illicit")) %>%
  group_by(year) %>%
  summarize(mean_cocaine_use = mean(illicit_drugs_cocaine_used_past_year),
            mean_illicit_abuse = mean(illicit_drugs_abuse_past_month),
            mean_illicit_dependence = mean(illicit_drugs_dependence_past_year),
            mean_illicit_treatment = mean(illicit_drugs_need_treatment_past_year)) %>%
  gather(key = "degree", value = "rate", -year) %>% 
  ggplot(aes(x = year, y = rate)) +
  geom_line(aes(color = degree)) +
  theme_bw() +
  labs(
    title = "Illicit drug use through years by degree",
    x = "Year",
    y = "Rate of illicit drug use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom") +
  scale_x_continuous(breaks = c(2002, 2006, 2010, 2014))

```

```{r drug_cocaine_state,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>% 
  select(year, state, age, contains("cocaine")) %>%
  group_by(state) %>%
  summarize(
    mean_past_year_cocaine_state = mean(illicit_drugs_cocaine_used_past_year)) %>%
  mutate(state = fct_reorder(state, mean_past_year_cocaine_state)) %>% 
  plot_ly(x = ~state, y = ~mean_past_year_cocaine_state, type = "bar", showlegend = FALSE, marker = list(color = ~state, showscale = FALSE))
```

* Illicit drug use by state

```{r illicit_state,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>% 
  group_by(state) %>% 
  summarize(mean_cocaine_use = mean(illicit_drugs_cocaine_used_past_year),
            mean_illicit_abuse = mean(illicit_drugs_abuse_past_month),
            mean_illicit_dependence = mean(illicit_drugs_dependence_past_year),
            mean_illicit_treatment = mean(illicit_drugs_need_treatment_past_year)) %>%
  gather(key = "degree", value = "rate", -state) %>% 
  ggplot(aes(x = state, y = rate)) +
  geom_bar(aes(fill = degree), stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Illicit drug use in each state by degree",
    x = "State",
    y = "Rate of illicit drug use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")
```

* Marijuana

```{r,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>%
  group_by(year, age) %>% 
  summarize(mean_marijuana_year = mean(marijuana_used_past_year)) %>% 
  ggplot(aes(x = year, y = mean_marijuana_year, color = age)) +
  geom_line() +
  theme_bw() +
  labs(
    title = "Marijuana use through years by age",
    x = "Year",
    y = "Rate of marijuana use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom") +
  scale_x_continuous(breaks = c(2002:2014))
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
drug_clean %>%
  group_by(state, age) %>% 
  summarize(mean_marijuana_year = mean(marijuana_used_past_year)) %>% 
  ggplot(aes(x = state, y = mean_marijuana_year)) +
  geom_bar(aes(fill = age), stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Marijuana use through state by age",
    x = "Year",
    y = "Rate of marijuana use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")

drug_clean %>%
  group_by(state) %>% 
  summarize(mean_marijuana_year = mean(marijuana_used_past_year)) %>% 
  mutate(state = fct_reorder(state, mean_marijuana_year)) %>% 
  ggplot(aes(x = state, y = mean_marijuana_year)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Marijuana use through state",
    x = "Year",
    y = "Rate of marijuana use",
    caption = "Data from drug_use"
  ) +
  theme(legend.position = "bottom")
```


