---
title: "p8105_Team34_Final_Project_Report"
author: "p8105_Final_Project_Team34"
date: "2018/12/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Motivation: Provide an overview of the project goals and motivation.



##Related work: Anything that inspired you, such as a paper, a web site, or something we discussed in class.



##Initial questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?


##Data: Source, scraping method, cleaning, etc.

1. Crime dataset

1.1 Data description

The data was collected by FBI's Uniform Crime Reporting (UCR) Program, which recorded different types of offenses by states, regions, or geographic divisions. The data presented each crime by volumn and rate per 100,000 inhabitants. Detailed description of columns were as follow:

 * state: state names
 
 * year: year the offense recorded
 
 * population: total population of the state
 
 * violent_crime_number/rate: violent crime involved force or threat of force against the victims. It included four types of offenses: murder and nonnegligent manslaughter, rape, robbery, and aggravated assault. 
 
 * columns containing murder manslaughter, rape, robbery, and aggravated assault were subdivision of violent crime
 
 * property_crime_number/rate: property crime indicated offenses involving property lost without force or threat of force. It included three types of offenses: burglary, larceny-theft, motor vehicle theft.
 
 * columns containing burglary, larceny-theft, and motor vehicle theft were subdivision of property crime

1.2 Data cleaning 

The crime dataset was loaded from the [google sheet](https://docs.google.com/spreadsheets/d/1iYhSFxs_IdRDrfrn1xqdK6uesNKWRjCIJ2GYloO0Ll8/edit#gid=249460096), detailed data cleaning steps were as follow:

 * Clean up column names using 'janitor' packages and manually delete the subscripts of text
 
 * Convert column 'area' from character to factor
 
 * Remove comma in columns containing numbers and rates, followed by transformation from character to numeric
 
 * Fill up area names where appropriate
 
 * Remove 'rape_legacy' related columns as it has overlapping information with 'rape_revise' columns
 
 * Remove NAs and create subsets by states, region, and geographic division

2. Drug dataset

2.1 Data description

This dataset is about substance abuse (cigarettes, marijuana, cocaine, alcohol) among different age groups (12-17, 18-25, 26 or above) and states in United States from year 2002 to 2014. Data was collected from individual state as part of the NSDUH study. 

2.2 Data cleaning

The dataset can be accessed through its [original website](https://think.cs.vt.edu/corgis/csv/drugs/drugs.html), detailed data cleaning steps were as follows: 
 
 * Mainly focused on the substance abuse of marijuana, illicit drug (cocaine) and alcohol, so selected all related columns from the whole dataset (state, year and rate of different substance abuse in different age groups)
 
 * Gathered all the columns except year and state
 
 * Replaced the strings before the age number for later separating
 
 * Separated the data into “age” and “rate” and obtained tidy dataset
 
 * Extracted population data from corresponding columns (three age groups) and kept “state” and “year” variables for later regression use
 

##Exploratory analysis: Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

* Scatter point plots of crime rate:

In order to visualize how the crime rate differs in different areas, regions and states, and how it change over time, we made scatter plots to show the differences at different geographic levels.

* Process of building shiny for drug data:

As we have 51 states, three types of drugs (marijuana, illicit drug, alcohol), three age groups (12-17, 18-25, 26 or above) and four or five degree in each drug (abuse, binge, dependence, need treatment, use). We wanted to analyze the distribution of degrees in each drug in each state through the years and also the distribution of degrees in each drug in each state and in a specific age group. Moreover, there were data for rate of perception risk in marijuana and alcohol use, so we further conducted analysis of the trend of perception risk in each age group and in each state for selected drug. Thus, we created three charts in total.

In chart A, we first filtered specific state and drug type been selected and then built an interactive bar chart with “year” as x axis, “rate” as y axis and different degree with different colors. In chart B, similarly we mainly focused on the change through years on what proportion of people in each state obtained perception of risk of a certain drug in different age groups. Thus, we filtered all perception risk rates and then assigned different color to each age group. In chart C, we attached the importance to the trend over years on different age groups in each drug type and in each state. As a result, we colored each degree to see the change in a certain group.





##Additional analysis: If you undertake formal statistical analyses, describe these in detail

* Linear Regression:

We are interested in the association between the crime rate and the drug use, so we undertake multivariable linear regression to test the significance of the estimated coefficients.
The rates of various crime types are considered to be the outcome, and the amount of drug (illicit drug, alcohol and marijuana) use, race proprtion of white people, rate of high school graduation are the predictors.

We checked the overal distribution of outcomes and variables using package "PerformanceAnalytics". Because of the relatively small sample size, the distributions could not be exactly normal, and we do not use transformation for the outcomes.

After we fit the models and obtain the results for each regression, we filter the estimated coefficients with p-value less than 0.05, we found that there are two outcomes (murder/manslaughter, robbery) are significantly related to drug use (illicit drug and marijuana). Then we run the diagnostics for these two multivariable linear regression models. There are two leverages and they are also influential points (Cook's distance > 0.5). These two influential points are from state "Hawaii" and "District of Columbia".

We try to remove these two outliers, and then fit models again. The R-squared and adjusted R-squared increase by approximately 0.3, indicating a higher goodness of fit. However, the estimated coefficients of drug use become unsiginficent (p-value > 0.05).

In conlusion, with data from Hawaii and District of Columbia, at 0.05 significant level, murder/manslaughter is negatively associated with illicit drug, while robbery and murder/manslaughter are positively associated with marijuana use. Without data from Hawaii and District of Columbia, at 0.05 significant level, the race proportion of white people and percentage of high school graduation become the main predictors. They are both negatively related to the outcomes (murder_manslughter_rate, robbery_rate, violent_crime_rate, aggravated_assault_rate, motor_vehicle_theft_rate, property_crime_rate, burglary_rate).

##Discussion: What were your findings? Are they what you expect? What insights into the data can you make?

Our finding are that, in general, the crime rate is highly related to alcohol, marijuana or illicit drug use. It is more associated to the race proportion of whites and the percentage of high school graduation.

These result are not we initially expect, as the crime rate is not highly significantly associated with these drug use.







