---
title: "About This Project"
output:
  html_document: 
    toc: true
    toc_float: true
---

# Source for our dataset

For this project we will use four datasets: 

*[Crime](https://ucr.fbi.gov/crime-in-the-u.s/2016/crime-in-the-u.s.-2016/tables/table-2) recorded crime rates in the United States in 2016; 

*[Drug](https://think.cs.vt.edu/corgis/csv/drugs/drugs.html) contains information of drug use among different age groups across states;

*[Education](https://en.wikipedia.org/wiki/List_of_U.S._states_by_educational_attainment) summarized the percentage of high school education across states;

*[Population Distribution by Race/Ethnicity](https://www.kff.org/other/state-indicator/distribution-by-raceethnicity/?currentTimeframe=0&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D) are based on the analysis of the Census Bureau’s American Community Survey (ACS) and may differ from other population estimates published yearly by the Census Bureau. U.S. and state population data displayed on this site are restricted to the civilian, non-institutionalized population for whom ACS collects and reports poverty information.





The crime dataset was derived from the Uniform Crime Reporting(UCR) program by FBI. The program collects real-world data for crime rate and law enforcement, and generates annual report. Here we will use the data from 2015 to 2016. The dataset for drug use was obtained from the National Survey on Drug Use and Health(NSDUH), which provides up-to-date survey results on alcohol, tabacco, drug use, etc.




















