---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
```

```{r data_cleaning}
drug_raw =
  read_csv("../data/drugs.csv") %>%
  janitor::clean_names()

drug_data = 
  drug_raw %>%
  select(year, state,
         rates_alcohol_abuse_past_year_12_17:rates_alcohol_dependence_past_year_26,
         rates_alcohol_need_treatment_past_year_12_17:rates_illicit_drugs_abuse_past_month_26, 
         rates_illicit_drugs_cocaine_used_past_year_12_17:rates_illicit_drugs_need_treatment_past_year_26,
         rates_marijuana_new_users_12_17:rates_marijuana_used_past_year_26) %>%
  gather(key, value, -state, -year) %>% 
  mutate(key = str_replace_all(key, c("year_" = "year:", "month_" = "month:", "risk_" = "risk:", "users_" = "users:"))) %>%
  separate(key, into = c("rate", "age"), sep = ":", extra = "merge") %>%
  mutate(rate = str_replace(rate, "^rates_", "")) %>% 
  spread(rate, value)

population_data = 
  drug_raw %>% 
  select(x12_17, x18_25:x26, year, state) %>% 
  gather(key = "age", value = "popul_in_thousands", -state, -year) %>% 
  mutate(age = str_replace(age, "x", ""))

drug_clean = left_join(drug_data, population_data)
```


```{r variable_for_shiny}
drug_choice = c("alcohol", "illicit", "marijuana")

state_choice = drug_clean %>% distinct(state) %>% pull()  

age_choice = c("Age 12-17", "Age 18-25", "Age 26 or above")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r creat_sidebars}
# selectInput widget
selectInput("state_choice", label = h3("Select state"),
            choices = state_choice, selected = "New York")

# radioButtons widget for drug choice
radioButtons("drug_choice", label = h3("Choose drug type"),
    choices = drug_choice, 
    selected = "marijuana")

# radioButtons widget for age group
radioButtons("age_choice", label = h3("Choose age group"),
    choices = age_choice, 
    selected = "Age 12-17")
```

Column {data-width=600}
-----------------------------------------------------------------------

### Drug use in whole population in states through years

```{r}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate (in thousands)")
  drug_clean %>% 
  filter(state == input$state_choice) %>%
  select(state, year, starts_with(input$drug_choice), -contains("perceptions")) %>% 
  gather(key = "degree", value = "rate", -year, -state) %>% 
  mutate(text_label = str_c("Degree: ", degree)) %>%   
    plot_ly(x = ~year, y = ~rate, type = "bar", color = ~degree, text = ~text_label) %>%  layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y)
})
```

Column {data-width=400}
-----------------------------------------------------------------------

### Perception risk of alcohol and marijuana in different age groups

```{r perception_risk}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate for Perception of Risk (in thousands)")  
drug_clean$age = recode(drug_clean$age, "12_17" = "Age 12-17", "18_25" = "Age 18-25", "26" = "Age 26 or above")
drug_clean %>% 
  filter(state == input$state_choice) %>%
  select(starts_with(input$drug_choice), year, age) %>% 
  select(year, age, contains("perceptions")) %>% 
  gather(-year, -age, key = "drug", value = "perception_risk") %>% 
  plot_ly(x = ~year, y = ~perception_risk, type = "bar", color = ~age) %>% 
  layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y)
})
```

### Drug use in states through years by age groups

```{r}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate (in thousands)")  
drug_clean$age = recode(drug_clean$age, "12_17" = "Age 12-17", "18_25" = "Age 18-25", "26" = "Age 26 or above")
drug_clean %>% 
  filter(state == input$state_choice, age == input$age_choice) %>%
  select(state, year, starts_with(input$drug_choice), 
         -contains("perceptions")) %>% 
  gather(key = "degree", value = "rate", -year, -state) %>% 
  mutate(text_label = str_c("Degree: ", degree)) %>%   
    plot_ly(x = ~year, y = ~rate, type = "bar", color = ~degree, text = ~text_label) %>%  layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y)
})
```

