---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(gsheet)
```

```{r crime_data}
#Read in Crime data
crime_raw = gsheet2tbl('https://docs.google.com/spreadsheets/d/1iYhSFxs_IdRDrfrn1xqdK6uesNKWRjCIJ2GYloO0Ll8/edit#gid=249460096') 
crime_raw = crime_raw[3:201,]

#Clean column names
crime = 
  crime_raw %>% 
  janitor::clean_names() %>% 
    rename_(population = names(.)[3],
          violent_crime_number = names(.)[4],
          violent_crime_rate = names(.)[5],
          murder_manslaughter_number = names(.)[6],
          murder_manslaughter_rate = names(.)[7],
          rape_revise_number = names(.)[8],
          rape_revise_rate = names(.)[9],
          rape_legacy_number = names(.)[10],
          rape_legacy_rate = names(.)[11],
          robbery_number = names(.)[12],
          robbery_rate = names(.)[13],
          aggravated_assault_number = names(.)[14],
          aggravated_assault_rate = names(.)[15],
          property_crime_number = names(.)[16],
          property_crime_rate = names(.)[17],
          burglary_number = names(.)[18],
          burglary_rate = names(.)[19],
          larceny_theft_number = names(.)[20],
          larceny_theft_rate = names(.)[21],
          motor_vehicle_theft_number = names(.)[22],
          motor_vehicle_theft_rate = names(.)[23]) %>% 
  mutate(area = as.factor(area)) 

# Remove comma and convert to numeric
crime[,3:23] <- as.numeric(gsub(",","",unlist(crime[,3:23])))

# fill up area name
i = 1
for (i in 0:65) {
  n = 3 * i + 1
  crime$area[n + 1] = paste0(crime$area[n]) 
  crime$area[n + 2] = paste0(crime$area[n])
  i = i + 1
}

#Select variables of interest and change to long format
crime_clean_rate =
  crime %>%
  filter(year != "Percent change") %>% 
  rename(state = area) %>% 
  filter(!state %in% c("United States Total", "Northeast", "Midwest", "South", "West", "New England", "Middle Atlantic", "East North Central", "West North Central", "South Atlantic", "East South Central", "West South Central", "Mountain", "Pacific", "Puerto Rico")) %>% 
  select(-rape_legacy_rate, -contains("number"), -population) %>%
  gather(key = crime_type, value = rate, -state, -year) %>% 
  mutate(rate = rate / 100)

#Make a table with state and state.abb 
state_abb =
  tibble(state = state.name) %>%
  bind_cols(tibble(abb = state.abb)) %>% 
  bind_rows(tibble(state = "District of Columbia", abb = "DC"))

#Add state.abb into crime_clean_rate
crime_with_abb = left_join(crime_clean_rate, state_abb, by = "state")
```

```{r drug_data}
#Read in drug data
drug_raw =
  read_csv("https://think.cs.vt.edu/corgis/csv/drugs/drugs.csv?forcedownload=1/drugs.csv") %>%
  janitor::clean_names()

#Tidy the drug data for mapping
drug_data_map = 
  drug_raw %>%
  select(year, state, contains("rates")) %>%
  select(year, state, contains("past_year")) %>%
  gather(key, value, -state, -year) %>% 
  mutate(key = str_replace(key, "year_", "year:")) %>%
  separate(key, into = c("rate", "age"), sep = ":", extra = "merge") %>%
  mutate(rate = str_replace(rate, "^rates_", "")) %>% 
  filter(rate != "pain_relievers_abuse_past_year") %>% 
  mutate(rate = str_replace_all(rate, c("alcohol_" = "alcohol:", "illicit_drugs_" = "illicit_drugs:", "marijuana_" = "marijuana:"))) %>%
  separate(rate, into = c("drug", "degree"), sep = ":", extra = "merge") %>%
  group_by(year, state, age, drug) %>%
  summarize(value = sum(value)) %>% 
  ungroup() %>% 
  spread(age, value) %>% 
  mutate(age_total = select(., "12_17":"26") %>% apply(1, sum, na.rm = TRUE)) %>%
  gather(key = age, value = value, "12_17":"age_total")


#Tidy the drug data for shiny bar plots
drug_clean = 
  drug_raw %>%
  select(year, state,
         rates_alcohol_abuse_past_year_12_17:rates_alcohol_dependence_past_year_26,
         rates_alcohol_need_treatment_past_year_12_17:rates_illicit_drugs_abuse_past_month_26, 
         rates_illicit_drugs_cocaine_used_past_year_12_17:rates_illicit_drugs_need_treatment_past_year_26,
         rates_marijuana_new_users_12_17:rates_marijuana_used_past_year_26) %>%
  gather(key, value, -state, -year) %>% 
  mutate(key = str_replace_all(key, c("year_" = "year:", "month_" = "month:", "risk_" = "risk:", "users_" = "users:"))) %>%
  separate(key, into = c("rate", "age"), sep = ":", extra = "merge") %>%
  mutate(rate = str_replace(rate, "^rates_", "")) 

#Drug population data
population_data = 
  drug_raw %>% 
  select(x12_17, x18_25:x26, year, state) %>% 
  gather(key = "age", value = "popul_in_thousands", -state, -year) %>% 
  mutate(age = str_replace(age, "x", ""))

#Final drug data for mapping
drug_clean_map = left_join(drug_data_map, population_data) #add population 
drug_with_abb = left_join(drug_clean_map, state_abb, by = "state") #add state.abb
```


```{r variable_for_shiny}
#Variables for crime
crime_choice = 
  crime_with_abb %>% 
  distinct(crime_type) %>% 
  pull()

year_choice = crime_with_abb %>% distinct(year) %>% pull()  

#Variables for drug
drug_choice = unique(drug_with_abb$drug) 

age_choice = c("Age 12-17", "Age 18-25", "Age 26 or above", "All age")

state_choice = drug_clean %>% distinct(state) %>% pull() 

year_choice_drug = unique(drug_with_abb$year)
```

Distributions of Crime Rates
=============================

Column {.sidebar}
-----------------------------------------------------------------------

```{r creat_sidebars_crime}
# selectInput widget for crime choice
selectInput("crime_choice", label = h3("Select Crime"),
            choices = crime_choice, selected = "murder_manslaughter_rate")

# radioButtons widget for crime year choice
radioButtons("year_choice", label = h3("Select Year (Crime)"),
             choices = year_choice, selected = 2016)
```


Column {data-width=600}
-----------------------------------------------------------------------

### Distributions of ten types of crime rates

```{r, crime_rates_map}
renderPlotly({
  l <- list(color = toRGB("white"), width = 2)
  g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
  
  crime_with_abb %>%
    filter(year == input$year_choice,
           crime_type == input$crime_choice) %>%
    mutate(text_label = str_c("Rate: ", rate, '\nState: ', state, ' Abb: ', abb, '\nYear: ', year)) %>% 
    plot_geo(locationmode = 'USA-states') %>%
  add_trace(
    z = ~rate, text = ~text_label, locations = ~abb,
    color = ~rate, colors = 'Greens'
  ) %>%
  colorbar(title = "Crime Rate (per 1,000)") %>%
  layout(
    title = 'Distribution of Crime Rate',
    geo = g
  )
}) #Crime rate map
```

Column {data-width=400}
-----------------------------------------------------------------------

### Barplot of crime rates by State

```{r Barplot_crime_state}
renderPlotly({
  crime_with_abb %>% 
    filter(year == input$year_choice,
           crime_type == input$crime_choice) %>%
    mutate(text_label = str_c("Rate: ", rate, '\nState: ', state, ' Abb: ', abb, '\nYear: ', year)) %>% 
    plot_ly(x = ~state, y = ~rate, text = ~text_label,
    marker = list(size = 10,
                       color = 'rgba(255, 182, 193, .9)',
                       line = list(color = 'rgba(152, 0, 0, .8)',
                                   width = 2))) %>%
  layout(title = 'Distribution of Crime Rate by State',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE))
}) #Crime rate by state (barplot)
```

Distributions of Drugs Use
====================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r, sidebars_drug}
# selectInput widget for drug choice
radioButtons("drug_choice", label = h3("Select Drug"),
            choices = drug_choice, selected = "marijuana")

# radioButtons widget for drug year choice
selectInput("year_choice_drug", label = h3("Select Year (Drug)"),
             choices = year_choice_drug, selected = "2014")

# radioButtons widget for age group
radioButtons("age_choice", label = h3("Choose Age Group"),
             choices = age_choice, selected = "Age 12-17")

# selectInput widget
selectInput("state_choice", label = h3("Select state"),
            choices = state_choice, selected = "New York")
```

Column {.tabset}
-----------------------------------------------------------------------

### Distributions of three types of drugs

```{r, Drug_distribution_map}
renderPlotly({
  l <- list(color = toRGB("white"), width = 2)
  g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

drug_with_abb$age = recode(drug_with_abb$age, "12_17" = "Age 12-17", "18_25" = "Age 18-25", "26" = "Age 26 or above", "age_total" = "All age")
  drug_with_abb %>%
    filter(year == input$year_choice_drug,
           drug == input$drug_choice,
           age == input$age_choice) %>%
    mutate(text_label = str_c("Rate: ", value, '\nState: ', state, ' Abb: ', abb, '\nYear: ', year, '\nDrug: ', drug, '\nAge group: ', age, '\nPopulation (in thousands): ', popul_in_thousands)) %>% 
    plot_geo(locationmode = 'USA-states') %>%
  add_trace(
    z = ~value, text = ~text_label, locations = ~abb,
    color = ~value, colors = 'Blues'
  ) %>%
  colorbar(title = "Drug Use Rate (per 1,000)") %>%
  layout(
    title = 'Distribution of Drug Use Rate',
    geo = g
  )
}) #Drug use rate map
```

### Drug Use in whole Population

```{r}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate (in thousands)")
  drug_clean %>% 
  filter(state == input$state_choice,
         str_detect(rate, input$drug_choice),
         !str_detect(rate, 'perceptions')) %>%
  plot_ly(x = ~year, y = ~value, type = "bar", color = ~rate) %>%  
    layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y,
           title = 'Drug Use in Whole Population in States Through Years')
})
```

### Perception Risk 

```{r perception_risk}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate for Perception of Risk (in thousands)")  
drug_clean$age = recode(drug_clean$age, "12_17" = "Age 12-17", "18_25" = "Age 18-25", "26" = "Age 26 or above")
drug_clean %>% 
  filter(state == input$state_choice,
         str_detect(rate, input$drug_choice),
         str_detect(rate, 'perceptions')) %>% 
  plot_ly(x = ~year, y = ~value, type = "bar", color = ~age) %>% 
  layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y,
         title = 'Perception Risk in Different Age Group')
})

```

### Drug Use by Age Groups

```{r}
renderPlotly({
x = list(title = "Year")
y = list(title = "Rate (in thousands)")  
drug_clean$age = recode(drug_clean$age, "12_17" = "Age 12-17", "18_25" = "Age 18-25", "26" = "Age 26 or above")
drug_clean %>% 
  filter(state == input$state_choice, 
         age == input$age_choice,
         str_detect(rate, input$drug_choice),
         !str_detect(rate, 'perceptions')) %>%
    plot_ly(x = ~year, y = ~value, type = "bar", color = ~rate) %>%  
  layout(legend = list(orientation = 'h'), xaxis = x, yaxis = y,
         title = 'Drug Use in States through Year by Age Groups')
})
```




